# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: appName
    volumes:
    - ./mongo:/data/db
    ports:
    - 27017:27017